{
 "title": "Liquidsoap",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "radio",
    "label": "Radio",
    "query": "label_values(liquidsoap_source_is_ready,radio)"
   },
   {
    "name": "type",
    "label": "Type",
    "query": "label_values(liquidsoap_source_is_ready,type)"
   },
   {
    "name": "name",
    "label": "Name",
    "query": "label_values(liquidsoap_source_is_ready,name)"
   }
  ]
 },
 "panels": [
  {
   "title": "$name Is Ready",
   "type": "stat",
   "description": "Is source $name ready to play",
   "repeat": "name",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "liquidsoap_source_is_ready{radio=~\"$radio\",type=~\"$type\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Now playing",
   "type": "stat",
   "description": "The real live source playing",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "liquidsoap_source_is_playing{radio=~\"$radio\"} > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Preferred Live Source",
   "type": "stat",
   "description": "The preferred live source to play",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "liquidsoap_source_is_preferred_livesource{radio=~\"$radio\"} > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Is output blank",
   "type": "stat",
   "description": "Is the output brodcasting blank audio",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "liquidsoap_source_is_blank{radio=~\"$radio\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Audio Levels for $radio (post encoder)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "LUFS" } },
   "targets": [
    {
     "expr": "liquidsoap_output_lufs_5s{radio=\"$radio\"}",
     "legendFormat": "{{radio}} 10s"
    },
    {
     "expr": "avg_over_time(liquidsoap_output_lufs_5s{radio=\"$radio\"}[1h])",
     "legendFormat": "{{radio}} 1h average"
    },
    {
     "expr": "avg_over_time(liquidsoap_output_lufs_5s{radio=\"$radio\"}[12h])",
     "legendFormat": "{{radio}} 12h average"
    }
   ]
  },
  {
   "title": "Output source playing history",
   "type": "graph",
   "description": "0 = source is not playling\n1 = source is playling",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "liquidsoap_source_is_playing{radio=~\"$radio\"}",
     "legendFormat": "{{type}} {{name}}"
    }
   ]
  },
  {
   "title": "Input / Output Ready",
   "type": "graph",
   "description": "0 = source unready\n1 = source ready",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "liquidsoap_source_is_ready{radio=~\"$radio\",type=~\"$type\",name=~\"$name\"}",
     "legendFormat": "{{type}} {{name}}"
    }
   ]
  },
  {
   "title": "Input / Output Duration Unready per second",
   "type": "graph",
   "description": "0 = source unready\n1 = source ready",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(liquidsoap_source_unready_duration_seconds{radio=~\"$radio\",type=~\"$type\",name=~\"$name\"}[1m])",
     "legendFormat": "{{type}} {{name}}"
    }
   ]
  },
  {
   "title": "SRT Input packet drop & loss rate (should be 0)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "packets" } },
   "targets": [
    {
     "expr": "ceil(rate(liquidsoap_srt_input_packet_drop_total{radio=\"$radio\",name=~\"$name\"}[30s]))",
     "legendFormat": " {{pod}} drop {{name}}"
    },
    {
     "expr": "ceil(rate(liquidsoap_srt_input_packet_loss_total{radio=\"$radio\",name=~\"$name\"}[30s]))",
     "legendFormat": " {{pod}} loss {{name}}"
    }
   ]
  },
  {
   "title": "SRT Input buffer length (should be linear)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "liquidsoap_srt_input_buffer_length{radio=\"$radio\",name=~\"$name\"}",
     "legendFormat": "{{pod}} {{name}}"
    }
   ]
  },
  {
   "title": "CPU usage per thread",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (threadname) (rate(namedprocess_namegroup_thread_cpu_seconds_total{groupname=\"liquidsoap\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}