---
name: Pre-release
on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  pre-release:
    name: Pre-release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Build artifacts via Makefile
        run: |
          mkdir -p dist
          CLEAN_REF=$(echo "$GITHUB_REF_NAME" | sed 's/[^a-zA-Z0-9]//g')
          VERSION="$CLEAN_REF-${GITHUB_SHA:0:7}"
          make artifact VERSION="$VERSION"
          ls -la dist
      - name: Create or update a draft pre-release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        with:
          name: "${{ github.ref_name }}"
          draft: true
          prerelease: true
          files: |
            dist/*.zip
            dist/*.md5
