---
name: Validation (commitlint)
on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Install commitlint
        run: npm install -D @commitlint/cli@21.0.2 @commitlint/config-conventional@21.0.2

      - name: In case of a push, validate only the last commit
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: In case of a PR, validate all the commits compared to the base branch
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
